### ISSUE TITLE
Official release through packagist.org?

### ISSUE THREAD

**Issue by OmniFaR** [easybill/zugferd-php#2]
This project looks promising but is development still active?
Any chance to get an official release which is available on packagist.org?

**Comment by Pag-Man** [comment]
Since I couldn't integrate the package, I wrote my own. Maybe it will help you: https://github.com/einfachArchiv/zugferd

**Comment by PATROMO** [comment]
Sorry, I did not notice the issue. I have publish this project on packagist.org.
