### ISSUE TITLE
Uncaught Error: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by geraldschwarz** [easybill/zugferd-php#30]
[Wed Nov 25 22:50:36.855512 2020] [proxy_fcgi:error] [pid 26804:tid 140112159565568] [client 93.208.26.207:50344] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /srv/www/vhosts/domain/httpdocs/xrechnung/vendor/jms/serializer/src/XmlSerializationVisitor.php:99\nStack trace:\n#0 /srv/www/vhosts/domain/httpdocs/xrechnung/vendor/jms/serializer/src/XmlSerializationVisitor.php(90): JMS\\Serializer\\XmlSerializationVisitor->createDocument()\n#1 /srv/www/vhosts/domain/httpdocs/xrechnung/vendor/jms/serializer/src/Visitor/Factory/XmlSerializationVisitorFactory.php(47): JMS\\Serializer\\XmlSerializationVisitor->__construct()\n#2 /srv/www/vhosts/domain/httpdocs/xrechnung/vendor/jms/serializer/src/Serializer.php(146): JMS\\Serializer\\Visitor\\Factory\\XmlSerializationVisitorFactory->getVisitor()\n#3 /srv/www/vhosts/domain/httpdocs/xrechnung/vendor/jms/serializer/src/Serializer.php(158): JMS\\Serializer\\Serializer->getVisitor()\n#4 /srv/www/vhosts/domain/httpdocs/xrechnung/vendor/easybill/zugferd-php/src/zugferd211/Builder.php(20): JMS\\Ser...'

**Comment by PATROMO** [comment]
https://stackoverflow.com/questions/14395239/class-domdocument-not-found
