### ISSUE TITLE
Missing ExemptionReason in TradeTaxType

### ISSUE THREAD

**Issue by thomaswacker** [easybill/zugferd-php#34]
In the file "FACTUR-X_EN16931_urn_un_unece_uncefact_data_standard_ReusableAggregateBusinessInformationEntity_100.xsd" there is a "ExemptionReason" in "TradeTaxType", that is missing in zugferd211/Model/TradeTax.php.

**Comment by PATROMO** [comment]
@thomaswacker we did not imply everything because it is not necessary. You can create a pull request at any time and help us to improve the software.

**Comment by thomaswacker** [comment]
Thanks. Its because mustang validator said:

A VAT Breakdown (BG-23) with the VAT Category code (BT-118) "Export outside the EU" shall have a VAT exemption reason code (BT-121), meaning "Export outside the EU" or the VAT exemption reason text (BT-120) "Export outside the EU" (or the equivalent standard text in another language).

Pull request will come soon.

**Comment by PATROMO** [comment]
The XSD said: `<xs:element name="ExemptionReason" type="udt:TextType" minOccurs="0"/>` **minOccurs="0"**. This means that it is not necessarily required.

**Comment by thomaswacker** [comment]
Thanks for fast merge!
