### ISSUE TITLE
PHP 7.4 required?

### ISSUE THREAD

**Issue by olleharstedt** [easybill/zugferd-php#36]
Any critical constructs used from PHP 7.4 that makes this library unusable for PHP 7.2?

**Comment by PATROMO** [comment]
No. But PHP 7.2 has reached the end of life and we dont support this. Feel free to fork and continue to support php 7.2.

**Comment by olleharstedt** [comment]
Got it, thanks!

**Comment by PATROMO** [comment]
We use only typed properties from php 7.4. If you fork this project you can easy drop this feature.

**Comment by olleharstedt** [comment]
Great, thanks. :)
