### ISSUE TITLE
Missing ReceivableSpecifiedTradeAccountingAccount, BT-133

### ISSUE THREAD

**Issue by olleharstedt** [easybill/zugferd-php#37]
Hi!

Thanks for your nice library! It seems like a field is missing for our use-case, correct me if I'm wrong.

System is German, GIZ Lieferantenporal.

Required field is BT-133, which seems to be called ReceivableSpecifiedTradeAccountingAccount

It should belong to this class, I think: https://github.com/easybill/zugferd-php/blob/master/src/zugferd211/Model/LineTradeSettlement.php

My source: https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/factur-x%20%28zugferd%202.0%29%20%5Bdraft%5D/factur-x%3B%20draft%3B%20en16931-conformant-extended.scm/html/021.htm?https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/factur-x%20%28zugferd%202.0%29%20%5Bdraft%5D/factur-x%3B%20draft%3B%20en16931-conformant-extended.scm/html/0244.htm

But there is says, name = "Booking reference". :thinking: 

Another source says BT-133 = "Invoice line Buyer accounting reference"

Would you accept a PR?

**Comment by olleharstedt** [comment]
Another source

![image](https://user-images.githubusercontent.com/607341/114589934-72c60f00-9c88-11eb-908d-f836c577d400.png)

**Comment by PATROMO** [comment]
Yes, you are right. It belongs in LineTradeSettlement.

```xml
<xs:complexType name="LineTradeSettlementType">
  <xs:sequence>
    <xs:element name="ApplicableTradeTax" type="ram:TradeTaxType" maxOccurs="unbounded"/>
    <xs:element name="BillingSpecifiedPeriod" type="ram:SpecifiedPeriodType" minOccurs="0"/>
    <xs:element name="SpecifiedTradeAllowanceCharge" type="ram:TradeAllowanceChargeType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="SpecifiedTradeSettlementLineMonetarySummation" type="ram:TradeSettlementLineMonetarySummationType"/>
    <xs:element name="AdditionalReferencedDocument" type="ram:ReferencedDocumentType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="ReceivableSpecifiedTradeAccountingAccount" type="ram:TradeAccountingAccountType" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>
```

Feel free to create a PR on it.

**Comment by PATROMO** [comment]
Ween need a new Class `TradeAccountingAccount`

```xml
<xs:complexType name="TradeAccountingAccountType">
  <xs:sequence>
    <xs:element name="ID" type="udt:IDType"/>
    <xs:element name="TypeCode" type="qdt:AccountingAccountTypeCodeType" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>
```

**Comment by olleharstedt** [comment]
Will you do this, or should I?

**Comment by olleharstedt** [comment]
PR here: https://github.com/easybill/zugferd-php/pull/38

**Comment by olleharstedt** [comment]
Want me to add a test to that?

**Comment by PATROMO** [comment]
Yes please. if it is possible.

**Comment by olleharstedt** [comment]
This is what my minimal test spits out:

```xml
      <ram:SpecifiedLineTradeSettlement>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>10.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
        <ram:ReceivableSpecifiedTradeAccountingAccount>
          <ram:ID>123</ram:ID>
          <ram:TypeCode>moo</ram:TypeCode>
        </ram:ReceivableSpecifiedTradeAccountingAccount>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
```

**Comment by olleharstedt** [comment]
That's fine?
