### ISSUE TITLE
PHP 7.4, unexpected 'ExchangedDocumentContext' (T_STRING)

### ISSUE THREAD

**Issue by Masegi** [easybill/zugferd-php#44]
Hi,

when I try to build a document I get this error:

PHP Parse error:  syntax error, unexpected 'ExchangedDocumentContext' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/app/data/vendor/easybill/zugferd-php/src/zugferd211/Model/CrossIndustryInvoice.php on line 26

I've tried php 7.2 to 8.1 but only got a progress on php 7.4. But there I get this error.

I've installed zugferd-php by composer and checked php modules. I'm using autoloader.

What am I doing wrong?

**Comment by PATROMO** [comment]
@Masegi we have Tests on php7.4 and and no errors. Which php7.4 version do you use? 
Did you perhaps accidentally change something in the source files?

**Comment by Masegi** [comment]
I use php 7.4.25 (cli)

No I havnt changed anything in your code.

**Comment by PATROMO** [comment]
@Masegi could you run the tests in Docker? 

I don't get any errors and unfortunately can't reproduce your problem....
![image](https://user-images.githubusercontent.com/318564/140048861-dc6b2ddb-d3d7-46fc-ac16-9f8a33cb75e7.png)

Is it possible for you to write a test that fails so that I can check this more accurately?

**Comment by Masegi** [comment]
![image](https://user-images.githubusercontent.com/5729517/140051444-f1c547d7-b2e3-4ced-9e36-255f816a55b2.png)
![image](https://user-images.githubusercontent.com/5729517/140051540-5960f7ad-3769-4ce7-909e-4004cbe14df9.png)


I've never worked with docker ...

**Comment by PATROMO** [comment]
Unfortunately I can not do anything with the error message. The code runs without problems with php 7.4. I need a code example from you to reproduce the error. Otherwise I can not help you.

**Comment by Masegi** [comment]
sry my bad, I only checked cli version but I had to enable/disable 7.4 apache mod
